Create Site page placeholders and minor changes done
gdscnitp/charges-by-tenant-landlord pull request #46
Opened 2022-01-27 20:54 UTC by anuj1511

2022-01-28 14:57 UTC, rishabhborn2win requested changes

2022-01-28 14:57 UTC, rishabhborn2win commented on pages/landing/particularSite.js
>    console.log(router.query.id);
remove these unwanted console.logs

2022-01-28 14:57 UTC, rishabhborn2win commented on pages/landing/particularSite.js
> +      enqueueSnackbar("Signin", { varient: "success" });
Not Relevant remove this line

2022-01-28 18:28 UTC, anuj1511 commented on pages/landing/particularSite.js
>    console.log(router.query.id);
Removed

2022-01-28 18:30 UTC, anuj1511 commented on pages/landing/particularSite.js
> +      enqueueSnackbar("Signin", { varient: "success" });
Done sir

2022-01-28 18:32 UTC, anuj1511 commented
Completed the suggested changes sir

2022-01-29 03:16 UTC, rishabhborn2win approved these changes

2022-01-29 03:16 UTC, merged